import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{ShoppingBag,Sparkles,Search,Plus,Minus,Trash2,ArrowRight,BrainCircuit,ShieldCheck,Zap,Star}from'lucide-react';import'./styles.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000/api';
function App(){const[products,setProducts]=useState([]),[cart,setCart]=useState({items:[],subtotal:0,total:0}),[q,setQ]=useState(''),[busy,setBusy]=useState(false),[agent,setAgent]=useState(null);const id='demo';
 const load=async()=>{setProducts(await fetch(`${API}/products?q=${encodeURIComponent(q)}`).then(r=>r.json()));setCart(await fetch(`${API}/cart/${id}`).then(r=>r.json()))};useEffect(()=>{load()},[]);
 const add=async p=>{setBusy(true);setCart(await fetch(`${API}/cart/${id}/items`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:p.id,quantity:1})}).then(r=>r.json()));setBusy(false)};
 const change=async(i,n)=>setCart(await fetch(`${API}/cart/${id}/items/${i.product_id}?quantity=${n}`,{method:'PATCH'}).then(r=>r.json()));
 const run=async()=>setAgent(await fetch(`${API}/agents/run`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'recommend products for my cart',cart_id:id})}).then(r=>r.json()));
 return <div><nav><div className="brand"><span className="logo">S</span> ShopStop <b>AI</b></div><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Search products, categories..."/></div><div className="navcart"><ShoppingBag size={21}/>{cart.items.length}<span>Cart</span></div></nav>
 <main><section className="hero"><div><div className="eyebrow"><Sparkles size={16}/> MULTI-AGENT COMMERCE</div><h1>Shopping that thinks<br/><em>with you.</em></h1><p>Discover products, optimize your basket and get intelligent recommendations powered by a coordinated AI agent team.</p><button onClick={run}>Ask the AI Concierge <ArrowRight size={18}/></button></div><div className="orb"><BrainCircuit size={100}/><span>5 agents<br/>working together</span></div></section>
 <section className="trust"><span><ShieldCheck/> Secure checkout</span><span><Zap/> Real-time pricing</span><span><Sparkles/> AI recommendations</span><span><Star/> 4.9 customer rating</span></section>
 <div className="layout"><section><div className="sectionhead"><div><small>CURATED FOR YOU</small><h2>Trending picks</h2></div><span>{products.length} products</span></div><div className="grid">{products.map(p=><article className="card" key={p.id}><div className={`visual ${p.color}`}><span>{p.emoji}</span><div className="rating"><Star size={13} fill="currentColor"/> {p.rating}</div></div><div className="cardbody"><small>{p.category}</small><h3>{p.name}</h3><p>{p.description}</p><div className="price">${p.price.toFixed(2)} <button disabled={busy} onClick={()=>add(p)}><Plus size={18}/></button></div></div></article>)}</div></section>
 <aside><div className="carthead"><div><small>YOUR BAG</small><h2>Cart <span>{cart.items.length}</span></h2></div><ShoppingBag/></div>{cart.items.length?<>{cart.items.map(i=><div className="line" key={i.id}><div className={`mini ${i.color}`}>{i.emoji}</div><div className="linetxt"><b>{i.name}</b><small>${i.price.toFixed(2)}</small><div className="qty"><button onClick={()=>change(i,i.quantity-1)}><Minus size={13}/></button>{i.quantity}<button onClick={()=>change(i,i.quantity+1)}><Plus size={13}/></button></div></div><button className="delete" onClick={()=>change(i,0)}><Trash2 size={16}/></button></div>)}<div className="totals"><span>Subtotal <b>${cart.subtotal.toFixed(2)}</b></span><span>Shipping <b>{cart.shipping?'$'+cart.shipping.toFixed(2):'FREE'}</b></span><span>Tax <b>${cart.tax.toFixed(2)}</b></span><strong>Total <b>${cart.total.toFixed(2)}</b></strong></div><button className="checkout">Checkout <ArrowRight/></button></>:<div className="empty">Your bag is waiting.<br/><small>Add something beautiful.</small></div>}
 {agent&&<div className="agent"><div className="agenttitle"><BrainCircuit/> AI orchestration trace</div>{agent.events.map(e=><div className="event"><span>✓</span><div><b>{e.agent}</b><small>{e.result}</small></div></div>)}</div>}</aside></div></main><footer>SHOPSTOP AI <span>•</span> Intelligent commerce demo • Built with React + FastAPI</footer></div>};createRoot(document.getElementById('root')).render(<App/>);
